ZADPRO/Remote-Radiology-Web-UI

src/components/date-picker.tsx

Updated date-picker.tsx for bugfix

Updated date-picker.tsx bugfix

---

src/pages/TechnicianPatientIntakeForm/AddintionalNotes.tsx
src/pages/TechnicianPatientIntakeForm/AllergiesMedications.tsx
src/pages/TechnicianPatientIntakeForm/BreastBiopsy.tsx
src/pages/TechnicianPatientIntakeForm/BreastSymptoms.tsx
src/pages/TechnicianPatientIntakeForm/PriorImaging.tsx
src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx
src/pages/TechnicianPatientIntakeForm/UploadDicoms.tsx
src/pages/ViewScanCenter/ViewScanCenter.tsx
src/services/technicianServices.ts

Added Pages for Technician In-Take form along with their services

Added Pages for Technician In-Take form

---

src/pages/PatientQueue/PatientQueue.tsx

Updated PatientQueue

---

src/services/dashboardService.ts
src/services/invoiceService.ts

Updated dashboard and invoice services

Updated dashboard and invoice services

---

src/pages/PatientFlow/MyCare.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/PatientQueue/PatientReport.tsx
src/pages/PatientQueue/UploadDicomFiles.tsx
src/pages/Report/BreastDensityandImageQuality/BreastDensityImageQuality.ts
src/pages/Report/BreastDensityandImageQuality/BreastDensityandImageQuality.tsx
src/pages/Report/BreastDensityandImageQuality/BreastDensityandImageQualityRight.tsx
src/pages/Report/ComparisonPrior/ComparisonPriorRight.tsx
src/pages/Report/GenerateReport/ComparisonPriorRight.tsx
src/pages/Report/GenerateReport/LesionsRightString.ts
src/pages/Report/GenerateReport/LymphNodes.ts
src/pages/Report/GrandularAndDuctalTissue/GrandularAndDuctalTissueRight.tsx
src/pages/Report/GrandularAndDuctalTissue/GrandularAndDuctalTissueRightReport.ts
src/pages/Report/ImpressionRecommendation.tsx
src/pages/Report/LeftReport.tsx
src/pages/Report/Lisons/LesionsOptions.tsx
src/pages/Report/Lisons/LesionsRightString.ts
src/pages/Report/Lisons/LisonsRight.tsx
src/pages/Report/LymphNodes/LymphNodesRight.tsx
src/pages/Report/NippleAreolaSkin/NippleAreolaSkin.tsx
src/pages/Report/Report.tsx
src/pages/Report/RightReport.tsx
src/services/reportService.ts

Updated Report and its related components

Updated Report and components

---

src/pages/Report/BreastDensityandImageQuality/BreastDensityImageQuality.ts
src/pages/Report/BreastImplantDetails/BreastImplantDetailsEditor.ts
src/pages/Report/GrandularAndDuctalTissue/GrandularAndDuctalTissueRightReport.ts
src/pages/Report/NippleAreolaSkin/NippleAreolaEditor.ts

Updated Report editor content - Changes

Updated Report editor content

---

src/pages/Report/GeneralReport.tsx

Updated GenerateReport.tsx - BugFix

Updated GenerateReport

---

src/pages/Report/GenerateReport/LesionsRight.tsx
src/pages/Report/ImpressionRecommendation.tsx
src/pages/Report/LeftReport.tsx
src/pages/Report/Lisons/LesionsOptions.tsx
src/pages/Report/NotesReport.tsx
src/pages/Report/Report.tsx
src/pages/Report/ReportQuestionsAssignment.ts
src/pages/Report/RightReport.tsx
src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx
src/services/reportService.ts

Updated Report and Technician In-Take form for BugFix

Updated code for BugFix

---

src/pages/Report/BreastDensityandImageQuality/BreastDensityImageQuality.ts
src/pages/Report/BreastImplantDetails/BreastImplantDetails.tsx
src/pages/Report/BreastImplantDetails/BreastImplantDetailsEditor.ts
src/pages/Report/GeneralReport.tsx
src/pages/Report/GrandularAndDuctalTissue/GrandularAndDuctalTissueRightReport.ts
src/pages/Report/NotesReport.tsx
src/pages/Report/Report.tsx
src/pages/Report/ReportQuestionsAssignment.ts
src/pages/Report/RightReport.tsx

Updated Technician InTake Form

Updated Report

---

src/pages/Dashboard/Dashboard.tsx
src/pages/Dashboard/MasterAdmin.tsx
src/pages/ManageWGPerformingProvider/EditWGPerformingProvider.tsx
src/pages/ManageWGPerformingProvider/ManageWGPerformingProvider.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/Routes/MainRoutes.tsx

Made Bugfixes

---

src/pages/Dashboard/RadiologyTrainingMaterial.tsx

Updated Radiology Training Materials -  BugFix

Technician in take form2

---

src/pages/Routes/UseIdleLogout.ts

Made code changes for fixing bugs.

Updated UseIdleLogout.ts

---

src/pages/PatientInTakeForm/PatientInTakeFormS/PersonalInformation.tsx

Updated PatientInTake - Personal Information

Updated PatientInTake - Personal Information

---

src/pages/Report/GenerateReport/DbFormReportGenerator.tsx

Updated Dbformreportgenerator

---

src/pages/PatientQueue/PatientQueue.tsx

Updated PatientQueue.tsx

---

src/pages/PatientInTakeForm/FormHeader.tsx
src/pages/PatientInTakeForm/MainInTakeForm.tsx
src/pages/PatientInTakeForm/PatientInTakeForm.tsx
src/pages/PatientInTakeForm/PatientInTakeFormDC/PatientInTakeForm04.tsx
src/pages/PatientInTakeForm/PatientInTakeFormDa/PatientInTakeForm02.tsx
src/pages/PatientInTakeForm/PatientInTakeFormDb/PatientInTakeForm03.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/FamilyHistory.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/MenstrualAndReproductive.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/PatientInTakeForm01.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/PersonalInformation.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/RiskStratification.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/PatientQueue/UploadDicomFiles.tsx
src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx

Display the patient's name, ID, and scan center code in the Patient Intake, Technician Intake, and DICOM Upload components.

Update the IntakeForm Name Replacement

---

src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx

Updated the Technician Intake Responsive

Update the Intake Form Service

---

src/pages/Report/GeneralReport.tsx

Updated GeneralReport - BugFix

Updated GeneralReport - BugFix

---

src/pages/AddRadiologist/AddRadiologist.tsx
src/pages/AddWellthGreenManager/AddManager.tsx

Updated AddRadiologist and AddManager

Updated AddRadiologist and AddManager

---

src/pages/PatientInTakeForm/PatientInTakeFormS/PatientInTakeForm01.tsx

Updated PatientInTake form

---

src/pages/PatientInTakeForm/PatientInTakeFormS/PatientInTakeForm01.tsx

Updated PatientInTakeForm

---

src/pages/Report/AutoPopulateReport.ts
src/pages/Report/ImpressionRecommendation.tsx
src/pages/Report/NotesReport.tsx
src/pages/Report/Report.tsx

Updated Code for ImpressionRecommendation

Updated Code for ImpressionRecommendation

---

src/components/QuillToolbar.tsx
src/components/TextEditor.tsx
src/pages/Report/Report.tsx

Updated TextEditor for Report

---

src/pages/Analytics/Analytics.tsx
src/pages/Analytics/ArtifactsPieChart.tsx
src/pages/Dashboard/MasterAdmin.tsx
src/pages/Dashboard/Notifications/Notification.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/Report/ComparisonPrior/ComparisonPriorRight.tsx
src/pages/Report/ComparisonPrior/ComparisonPriorRightString.ts
src/pages/Report/GeneralReport.tsx
src/pages/Report/GenerateReport/LymphNodes.ts
src/pages/Report/ImpressionRecommendation.tsx
src/pages/Report/LeftReport.tsx
src/pages/Report/Lisons/LesionsOptions.tsx
src/pages/Report/Lisons/LesionsRightString.ts
src/pages/Report/Lisons/LisonsRight.tsx
src/pages/Report/NotesReport.tsx
src/pages/Report/PatientHistory.tsx
src/pages/Report/Report.tsx
src/pages/Report/RightReport.tsx
src/pages/TechnicianPatientIntakeForm/AddintionalNotes.tsx
src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx
src/services/analyticsService.tsx
src/services/notificationService.ts
src/services/reportService.ts
src/services/technicianServices.ts

Updated the Addendum, Artifacts Analytics, and Notifications. Added an Image Text Editor for individual reports.

Report enhancement

---

src/pages/Report/Report.tsx

Updated the Report Question Count

---

src/pages/Report/ComparisonPrior/ComparisonPriorRight.tsx
src/pages/Report/GeneralReport.tsx
src/pages/Report/LeftReport.tsx
src/pages/Report/Lisons/LesionsOptions.tsx
src/pages/Report/Report.tsx
src/pages/Report/RightReport.tsx

Updated the Placeholder for the Image Preview and Report Back Button Bug Fix

Updated the Placeholder for the Image Preview and Report Back Button Bug Fix

---

src/pages/TechnicianPatientIntakeForm/BreastSymptoms.tsx

Updated Technician Required

---

src/pages/Report/GenerateReport/LymphNodes.ts
src/pages/Report/Lisons/LesionsRightString.ts
src/pages/Report/LymphNodes/LymphNodesRight.tsx

Updated the Lesions string sentence and adding the sagital lymphnode

Updated the Lesions string sentence and adding the sagital lymphnode

---

package-lock.json
package.json
src/pages/Analytics/Analytics.tsx
src/pages/Analytics/ScanCenterOverAllAnalaytics.tsx
src/pages/Analytics/TATPieChart.tsx
src/pages/Analytics/UsersOverAllAnalyticsTable.tsx
src/pages/Dashboard/InvoiceOverAllTable.tsx
src/pages/Dashboard/InvoicePopUp.tsx
src/pages/Report/NotesReport.tsx
src/pages/Report/Report.tsx

Download the Excel Analytics and Changes in Invoice

Download the Excel Analytics and Changes in Invoice

---

src/pages/AddRadiologist/AddRadiologist.tsx
src/pages/AddScribe/AddScribe.tsx
src/pages/AddTechnician/AddTechnician.tsx
src/pages/AddWGPerformingProvider/AddWGPerformingProvider.tsx

Required File Bug Fix

---

src/pages/Analytics/ArtifactsPieChart.tsx
src/pages/Analytics/ScanIndicationsPie.tsx
src/pages/Analytics/TATPieChart.tsx

Updated Analytics Color

---

src/pages/Dashboard/MasterAdmin.tsx
src/pages/Report/Lisons/LesionsRightString.ts

Updated the Sentence Correction

Updated the Sentence Correction

---

src/pages/PatientQueue/PatientQueue.tsx
src/pages/Report/Report.tsx

Updated the Report Enhancement Optimization

Updated the Report Enhancement Optimization

---

src/pages/Report/ComparisonPrior/ComparisonPriorRightString.ts

Updated the Comparison Text

---

src/pages/Analytics/Analytics.tsx

Update the Artificates

---

src/pages/Report/Report.tsx

Updated Impression Bug Fix

---

src/pages/ManagePatient/EditPatient.tsx
src/pages/PatientFlow/MyCare.tsx
src/pages/PatientInTakeForm/PatientInTakeFormS/PersonalInformation.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/Report/NippleAreolaSkin/NippleAreolaEditor.ts
src/pages/Report/Report.tsx
src/pages/TechnicianPatientIntakeForm/TechnicianPatientIntakeForm.tsx
src/pages/ViewScanCenter/ViewScanCenter.tsx
src/services/scancenterService.ts
src/utlis/downloadReportsPdf.ts

Updated the Changes

---

src/pages/PatientQueue/PatientQueue.tsx

Update the Patient CustId Access

Update the Patient CustId Access

---

src/pages/Login/ResetPassword.tsx
src/pages/PatientQueue/PatientQueue.tsx
src/pages/Report/NotesReport.tsx
src/pages/Report/Report.tsx
src/pages/TechnicianPatientIntakeForm/AllergiesMedications.tsx
src/services/reportService.ts

Updated the Reset password Page logo bug Fix, Update the patient Queue Public, private color Change, introducing the new addendum macro sentence concept, Adding the Performing Provider and Verifying provider name in the Report

Updated the Logo Fix, Public private Color Change, Adding new concept  in the Addendum and adding the performing, Reviewer name in the report

---

src/pages/TechnicianPatientIntakeForm/AllergiesMedications.tsx

Updated the Fix at technician Bug fix

Updated the Fix at technician Bug fix
